// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-IronSource",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-IronSource", targets: ["AATKit-IronSource"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-IronSource",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    "AATIronSourceAdapter",
                    "AATIronSourceAdQualitySDK",
                    "AATIronSource",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-IronSource"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATIronSourceAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/AATIronSourceAdapter.zip",
            checksum: "ee4ef9dcf241d06ce3aa09ce28f6a9bfb31a35d9d8b4b670398c34546450eb43"
        ),
        .binaryTarget(
            name: "AATIronSourceAdQualitySDK",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/IronSourceAdQualitySDK.zip",
            checksum: "aef5b794af7e72eab77da4637c9a80cd4e4adb3e1353d91d778995e0053ec936"
        ),
        .binaryTarget(
            name: "AATIronSource",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/IronSource.zip",
            checksum: "3e70acf924c0bd0c68f37c5efa7b11daec417718488773960ba89b9e9e2c7e92"
        ),
    ]
)
