// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-IronSource",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-IronSource", targets: ["AATKit-IronSource"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0-beta2"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-IronSource",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    "AATIronSourceAdapter",
                    "AATIronSourceAdQualitySDK",
                    "AATIronSource",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-IronSource"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATIronSourceAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/AATIronSourceAdapter.zip",
            checksum: "69284de0ec0a631411f65bfc04341782759419dbf6635a1bd5150052c8408ecf"
        ),
        .binaryTarget(
            name: "AATIronSourceAdQualitySDK",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/IronSourceAdQualitySDK.zip",
            checksum: "c5952ab47fca543334b3c6c7e707a5556ae12858a527086a88dfc27529f2e505"
        ),
        .binaryTarget(
            name: "AATIronSource",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/IronSource.zip",
            checksum: "28e6188f1e91ae3e460ffb5338448b1b46bed2f0351aec554bd5480ce2ec11b9"
        ),
    ]
)
