// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-IronSource",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-IronSource", targets: ["AATKit-IronSource"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0-beta3"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-IronSource",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    "AATIronSourceAdapter",
                    "AATIronSourceAdQualitySDK",
                    "AATIronSource",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-IronSource"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATIronSourceAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/AATIronSourceAdapter.zip",
            checksum: "5589e7935131bf67c8b6dc265cda3904c29f9d580b2eb612cda323cfc74674fa"
        ),
        .binaryTarget(
            name: "AATIronSourceAdQualitySDK",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/IronSourceAdQualitySDK.zip",
            checksum: "bf79cf91590935f895fc0c0c2e130f44432c467322e7a4eff89f172f023fe06f"
        ),
        .binaryTarget(
            name: "AATIronSource",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/IronSource.zip",
            checksum: "d4910fe37e4054657823286967225caa19d97e56b1df1551e81fa05b6990ca83"
        ),
    ]
)
